### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
!pip install tensorflow

In [4]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### Vocabulary size
voc_size= 500

#### One Hot Representation

In [11]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[443, 381, 192, 180], [443, 381, 192, 333], [443, 244, 192, 418], [225, 270, 243, 39, 27], [225, 270, 243, 39, 444], [357, 443, 203, 192, 224], [159, 111, 161, 39]]


### Word Embedding Represntation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [13]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 443 381 192 180]
 [  0   0   0   0 443 381 192 333]
 [  0   0   0   0 443 244 192 418]
 [  0   0   0 225 270 243  39  27]
 [  0   0   0 225 270 243  39 444]
 [  0   0   0 357 443 203 192 224]
 [  0   0   0   0 159 111 161  39]]


In [17]:
## post padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[443 381 192 180   0   0   0   0]
 [443 381 192 333   0   0   0   0]
 [443 244 192 418   0   0   0   0]
 [225 270 243  39  27   0   0   0]
 [225 270 243  39 444   0   0   0]
 [357 443 203 192 224   0   0   0]
 [159 111 161  39   0   0   0   0]]


In [18]:
## 10 feature dimesnions
dim=10


In [22]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,
                    output_dim=10,
                    input_shape= (sent_length,)))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
##'the glass of milk',
embedded_docs[0]

array([443, 381, 192, 180,   0,   0,   0,   0], dtype=int32)

In [27]:
print(sent_length)
print(embedded_docs[0].shape)

8
(8,)


In [29]:
import numpy as np
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step


array([[[ 0.00058131,  0.0191784 , -0.02958214,  0.00490887,
         -0.00203907,  0.01953336,  0.01807156, -0.00112535,
         -0.01340721, -0.0052911 ],
        [-0.01303805, -0.01271448,  0.02201834,  0.01710761,
          0.03162105, -0.04017044,  0.00067683,  0.0167484 ,
         -0.04094347,  0.03971287],
        [ 0.04222612, -0.0214772 ,  0.01688466,  0.02308257,
         -0.01525677,  0.01050471,  0.00757638,  0.00550069,
         -0.04071975, -0.02090087],
        [-0.02670648,  0.00214045, -0.00700295,  0.00946974,
         -0.03471845, -0.02909683,  0.03459985,  0.00998479,
         -0.0098927 ,  0.04202112],
        [ 0.02795944, -0.00646633,  0.02957977,  0.04195471,
         -0.02388721,  0.00796264,  0.03823591, -0.02665002,
         -0.01105078, -0.01358619],
        [ 0.02795944, -0.00646633,  0.02957977,  0.04195471,
         -0.02388721,  0.00796264,  0.03823591, -0.02665002,
         -0.01105078, -0.01358619],
        [ 0.02795944, -0.00646633,  0.02957977,  0.0

In [30]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
[[[ 0.00058131  0.0191784  -0.02958214  0.00490887 -0.00203907
    0.01953336  0.01807156 -0.00112535 -0.01340721 -0.0052911 ]
  [-0.01303805 -0.01271448  0.02201834  0.01710761  0.03162105
   -0.04017044  0.00067683  0.0167484  -0.04094347  0.03971287]
  [ 0.04222612 -0.0214772   0.01688466  0.02308257 -0.01525677
    0.01050471  0.00757638  0.00550069 -0.04071975 -0.02090087]
  [-0.02670648  0.00214045 -0.00700295  0.00946974 -0.03471845
   -0.02909683  0.03459985  0.00998479 -0.0098927   0.04202112]
  [ 0.02795944 -0.00646633  0.02957977  0.04195471 -0.02388721
    0.00796264  0.03823591 -0.02665002 -0.01105078 -0.01358619]
  [ 0.02795944 -0.00646633  0.02957977  0.04195471 -0.02388721
    0.00796264  0.03823591 -0.02665002 -0.01105078 -0.01358619]
  [ 0.02795944 -0.00646633  0.02957977  0.04195471 -0.02388721
    0.00796264  0.03823591 -0.02665002 -0.01105078 -0.01358619]
  [ 0.02795944 -0.00646633  0.02957977  0.04195471 -0.02388721
    0.007

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]